### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by NullKioo** [TwoOnefour/youthstudy#1]
python3 youthSpider.py
Traceback (most recent call last):
  File "/root/youthstudy/youthSpider.py", line 145, in <module>
    spider.run()
  File "/root/youthstudy/youthSpider.py", line 32, in run
    self.submit_data(self.get_data())
  File "/root/youthstudy/youthSpider.py", line 51, in submit_data
    'username': n["h5_ask_member"]["name"],
TypeError: string indices must be integers

**Comment by TwoOnefour** [comment]
请问有传入openid吗

**Comment by TwoOnefour** [comment]
提供一下你的openid让我复现一下

**Comment by TwoOnefour** [comment]
可能是你的openid不正确导致的。openid获取方式请参考readme中的相关说明

**Comment by TwoOnefour** [comment]
@1955782864 可能是你的openid不正确导致的，获取方式请参考readme中的Submit information
